src/src_app/app/views/register.py
from flask import Blueprint, render_template, request
from app.models import db, Cultivo, Component, Device
from app.models import DetaileDevice
from app.models import CultivoDevice
from app.models import Broker
import json

register = Blueprint('register', __name__)


@register.route('/broker_config', methods=['GET', 'POST'])
def broker_config():
    print("broker config")
    data = [broker._asdict() for broker in db.session.query(Broker)]
    if request.form:
        print(request.form)
        db.session.add(broker_db(request.form))
        db.session.commit()
        broker_config = {
                'topic':request.form['topic'],
                'broker':request.form['ip_broker'],
                'port':request.form['port']}
        from app.background import create_sensor_mqtt, create_action_mqtt
        task_action = create_sensor_mqtt.delay(broker_config)
        task_action = create_action_mqtt.delay(broker_config)
    return render_template('register/broker_config.html', data=data)




@register.route('/cultivo', methods=['GET', 'POST'])
def cultivo():
    print("registrar cultivo")
    data = [cultivo._asdict() for cultivo in db.session.query(Cultivo)]
    if request.form:
        print(request.form)
        db.session.add(cultivo_db(request.form))
        db.session.commit()
    return render_template('register/cultivo.html', data=data)




@register.route('/device', methods=['GET', 'POST'])
def device():
    print("registrar device")
    data = [device._asdict() for device in db.session.query(Device)]
    if request.form:
        print(request.form)
        db.session.add(device_db(request.form))
        db.session.commit()
    return render_template('register/device.html', data=data)



@register.route('/component', methods=['GET', 'POST'])
def component():
    print("registrar component")
    data = [cultivo._asdict() for cultivo in db.session.query(Component)]
    if request.form:
        print(request.form)
        db.session.add(component_db(request.form))
        db.session.commit()
    return render_template('register/component.html', data=data)



@register.route('/device_component', methods=['GET', 'POST'])
def device_component():
    print("registrar detaile_device")
    data = dict()
    data['device'] = [device._asdict() for device in db.session.query(Device)]
    data['component'] = [cultivo._asdict() for cultivo in db.session.query(Component)]
    data['detaile_device'] = [dd for dd in db.session.query(DetaileDevice, Device, Component).join(Component).join(Device)]
    print(data['detaile_device'])
    if request.form:
        print(request.form)
        db.session.add(detaile_device_db(request.form))
        db.session.commit()
    return render_template('register/device_component.html', data=data)



@register.route('/cultivo_device', methods=['GET', 'POST'])
def cultivo_device():
    print("Asignar device to component")
    data = dict()
    data['device'] = [device._asdict() for device in db.session.query(Device)]
    data['cultivo'] = [cultivo._asdict() for cultivo in db.session.query(Cultivo)]
    data['cultivo_device'] = [cd for cd in db.session.query(CultivoDevice, Cultivo, Device).join(Cultivo).join(Device)]
    print(data['cultivo_device'])
    if request.form:
        print(request.form)
        db.session.add(cultivo_device_db(request.form))
        db.session.commit()
    return render_template('register/cultivo_device.html', data=data)






## helpers

def broker_db(data):
    print(data)
    broker = Broker()
    broker.ip_broker = data['ip_broker']
    broker.topic = data['topic']
    broker.port = data['port']
    return broker



def cultivo_db(data):
    print(data)
    cultivo = Cultivo()
    cultivo.name = data['name']
    cultivo.lenght = data['lenght']
    cultivo.hight = data['hight']
    cultivo.type_cultivo = data['type_cultivo']
    return cultivo


def component_db(data):
    print(data)
    component = Component()
    component.model = data['model']
    component.marca = data['marca']
    component.variable = data['variable']
    component.function = data['function']
    component.num_pin = data['num_pin']
    return component



def device_db(data):
    print(data)
    device = Device()
    device.model = data['model']
    device.marca = data['marca']
    device.function = data['function']
    return device


def detaile_device_db(data):
    print(data)
    dd = DetaileDevice()
    dd.device_id = data['device']
    dd.component_id = data['component']
    return dd


def cultivo_device_db(data):
    print(data)
    cd = CultivoDevice()
    cd.cultivo_id = data['cultivo']
    cd.device_id = data['device']
    cd.state = ''
    return cd

src/src_app/app/templates/register/action.html
{% extends 'base/base.html' %}
{% block content %}

{% endblock %}

src/src_app/app/templates/register/broker_config.html
{% extends 'base/base.html' %}
{% block content %}


<div class="container">
<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ip broker</th>
                    <th scope="col">Topico</th>
                    <th scope="col">Puerto</th>
                </tr>
            </thead>
            <tbody>
                    {% for device in data %}
                <tr>
                    <th scope="row">{{device.id}}</th>
                    <td>{{device.ip_broker}}</td>
                    <td>{{device.topic}}</td>
                    <td>{{device.port}}</td>
                </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-xl-10">
        <form action="{{url_for('register.broker_config')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <input type="text" class="form-control" name="ip_broker" placeholder="Ip broker">
                </div>
                <div class="col">
                    <input type="text" class="form-control"  name="topic" placeholder="Topic">
                </div>
                <div class="col">
                    <input type="text" class="form-control" name="port" placeholder="Port">
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary">+</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

src/src_app/app/templates/register/component.html
{% extends 'base/base.html' %}
{% block content %}


<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Model</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Variable</th>
                    <th scope="col">Función</th>
                    <th scope="col">Estado</th>
                    <th scope="col">N° Pin</th>
                </tr>
            </thead>
            <tbody>
                    {% for component in data %}
                <tr>
                    <th scope="row">{{component.id}}</th>
                    <td>{{component.model}}</td>
                    <td>{{component.marca}}</td>
                    <td>{{component.variable}}</td>
                    <td>{{component.function}}</td>
                    <td>{{component.state}}</td>
                    <td>{{component.num_pin}}</td>
                </tr>
                    {% endfor %}
            </tbody>
        </table>
    <div class="col-xl-10">
        <form action="{{url_for('register.component')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <input type="text" class="form-control" name="model" placeholder="Model">
                </div>
            <div class="col">
                <input type="text" class="form-control"  name="marca" placeholder="Marca">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="variable" placeholder="Variable">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="function" placeholder="Función">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="state" placeholder="Estado">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="num_pin" placeholder="N° Pin">
            </div>

            <div class="col">
                <button type="submit" class="btn btn-primary">+</button>
            </div>
        </div>
    </form>
    </div>
</div>

{% endblock %}

src/src_app/app/templates/register/cultivo.html
{% extends 'base/base.html' %}
{% block content %}

<div class="container">
    
<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Hight</th>
                    <th scope="col">Lenght</th>
                    <th scope="col">Tipo cultivo</th>
                </tr>
            </thead>
            <tbody>
                    {% for cultivo in data %}
                <tr>
                    <th scope="row">{{cultivo.id}}</th>
                    <td>{{cultivo.name}}</td>
                    <td>{{cultivo.hight}}</td>
                    <td>{{cultivo.lenght}}</td>
                    <td>{{cultivo.type_cultivo}}</td>
                </tr>
                    {% endfor %}
            </tbody>
        </table>
    <div class="col-xl-6">
        <form action="{{url_for('register.cultivo')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <input type="text" class="form-control" name="name" placeholder="Nombre">
                </div>
            <div class="col">
                <input type="text" class="form-control"  name="hight" placeholder="hight">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="lenght" placeholder="lenght">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="type_cultivo" placeholder="Tipo cultivo">
            </div>

            <div class="col">
                <button type="submit" class="btn btn-primary">+</button>
            </div>
        </div>
    </form>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <form action="{{url_for('register.cultivo_device')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <button type="submit" class="btn btn-secondary btn-lg btn-block">Asociar device</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

src/src_app/app/templates/register/cultivo_device.html
{% extends 'base/base.html' %}
{% block content %}


<div class="container">
<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre cultivo</th>
                    <th scope="col">Nombre  componente</th>
                </tr>
            </thead>
            <tbody>

            {% for dd in data.cultivo_device %}
                <tr>
                    <th scope="row"> {{dd[0].id}}</th>
                    <td>{{dd[1].name}}</td>
                    <td>{{dd[2].model}}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="col-xl-10">
        <form action="{{url_for('register.cultivo_device')}}" method="POST" >
          <div class="form-row align-items-center">
            <div class="col-auto my-1">
              <select name="cultivo" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                <option selected>Cultivo...</option>
                {% for cultivo in data.cultivo %}
                <option value={{cultivo.id}}>{{cultivo.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-auto my-1">
              <select name="device" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                <option selected>Device...</option>
                {% for device in data.device %}
                <option value={{device.id}}>{{device.model}} </option>
                {% endfor %}
              </select>
            </div>
            </div>
           <div class="col-auto my-1">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

src/src_app/app/templates/register/device.html
{% extends 'base/base.html' %}
{% block content %}


<div class="container">
<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Model</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Función</th>
                </tr>
            </thead>
            <tbody>
                    {% for device in data %}
                <tr>
                    <th scope="row">{{device.id}}</th>
                    <td>{{device.model}}</td>
                    <td>{{device.marca}}</td>
                    <td>{{device.function}}</td>
                </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-xl-10">
        <form action="{{url_for('register.device')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <input type="text" class="form-control" name="model" placeholder="Modelo">
                </div>
                <div class="col">
                    <input type="text" class="form-control"  name="marca" placeholder="Marca">
                </div>
                <div class="col">
                    <input type="text" class="form-control" name="function" placeholder="Función">
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary">+</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <form action="{{url_for('register.device_component')}}" method="POST" >
            <div class="form-row">
                <div class="col">
                    <button type="submit" class="btn btn-secondary btn-lg btn-block">Asociar componentes</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

src/src_app/app/templates/register/device_component.html
{% extends 'base/base.html' %}
{% block content %}


<div class="container">
<div class="row">
    <div class="col-xl-12">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre dispositivo</th>
                    <th scope="col">Nombre  componente</th>
                </tr>
            </thead>
            <tbody>

            {% for dd in data.detaile_device %}
                <tr>
                    <th scope="row"> {{dd[0].id}}</th>
                    <td>{{dd[1].model}}</td>
                    <td>{{dd[2].model}}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="col-xl-10">
        <form action="{{url_for('register.device_component')}}" method="POST" >
          <div class="form-row align-items-center">
            <div class="col-auto my-1">
              <select name="device" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                <option selected>Dispositivo</option>
                {% for device in data.device %}
                <option value={{device.id}}>{{device.model}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-auto my-1">
              <select name="component" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                <option selected>Componente</option>
                {% for component in data.component %}
                <option value={{component.id}}>{{component.model}} </option>
                {% endfor %}
              </select>
            </div>
            </div>
           <div class="col-auto my-1">
              <button type="submit" class="btn btn-primary">Subir</button>
            </div>
          </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

src/src_app/app/templates/register/index.html
{% extends 'base/base.html' %}
{% block content %}

{% endblock %}

src/src_app/app/templates/register/sensor.html
{% extends 'base/base.html' %}
{% block content %}




{% endblock %}