src/src_app/app/views/home.py
from flask import Blueprint, render_template, request
from app.models import db, Measure, Cultivo, DetaileDevice, CultivoDevice, Component, Device
import json
from datetime import datetime
from app.sensor import Sensor


home = Blueprint('home', __name__)

COLORES = {
        'LUZ': "card text-white bg-warning mb-3",
        'TEM': "card text-white bg-danger mb-3",
        'HUM_SOIL': "card text-white bg-success mb-3",
        'HUM':"card text-white bg-primary mb-3"
        }


@home.route('/', methods=['GET', 'POST'])
def index():
    data = dict()
    cultivos = [cultivo for cultivo in db.session.query(Cultivo)]
    r_cultivo = request.form.get('num_cultivo')
    select = 1
    if r_cultivo:
        select = r_cultivo
    components  = [(c.id, c.variable)  for c in db.session.query(Component).join(DetaileDevice).join(Device).join(CultivoDevice).filter(CultivoDevice.cultivo_id == select, Component.function=='sensor')]
    print(components)
    for c_id, c_var in components:
        data[c_var] = [med.value for med in  db.session.query(Measure).order_by(Measure.date_created.desc()).filter(Measure.component_id == c_id, Measure.cultivo_id == select).limit(1)]
    print(data)
    data_template={
            "colores":COLORES,
            "data":data,
            "select":r_cultivo
            }
    return render_template('home/index.html', colores=COLORES, data=data, cultivos=cultivos, select=r_cultivo)

src/src_app/app/templates/home/index.html
{% extends 'base/base.html'%}
{% block content %}

<div class="row">
    <div class="col-2">
         <form action="{{url_for('home.index')}}" method="POST">
            <select id="cultivo_select" name="num_cultivo" class="custom-select">
                {% for cultivo in cultivos %}
                <option value={{cultivo.id}}>{{cultivo.name}} </option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-default">Ir</button>
        </form>
    </div>
    <div class="col-10">
        <!-- graficos -->
    <div class="container">	</div>
    </div>
</div>


<div class="container">
    {% for var in data %}
    <div class= "{{colores[var]}}" style="max-width: 18rem;">
            <div class="card-header">{{var}}</div>
    <div class="card-body">
        <h5 class="card-title">{{data[var][0]}}</h5>
    </div>
</div>
{% endfor %}


</div>



<script charset="utf-8">
$(function() {
console.log( {{select}} )
$("select option[value=" + {{select}} + "]").attr("selected",true);
})
</script>


{% endblock %}