src/src_app/app/views/huerta.py
from flask import Blueprint, render_template, request
from app.models import db, Measure, Cultivo, DetaileDevice, Component, Action, Device, CultivoDevice
import json
from datetime import datetime

huerta = Blueprint('huerta', __name__)


@huerta.route('/huerta', methods=['GET', 'POST'])
def index():
    check = {'false':0, 'true':1}
    cultivos = [cultivo for cultivo in db.session.query(Cultivo)]
    r_cultivo = request.form.get('num_cultivo')
    actions = dict()
    if r_cultivo:
         actions  = [ act._asdict() for act in db.session.query(Component).join(DetaileDevice).join(Device).join(CultivoDevice).filter(CultivoDevice.cultivo_id == r_cultivo, Component.function=='action')]
         print(actions)
    state = request.form.get('state')
    r_component = request.form.get('id')
    cultivo_id = request.form.get('cultivo_id')
    if state:
        data = {'cultivo_id':cultivo_id,
                'component_id':r_component,
                'time_action':datetime.now(),
                'state':'0',
                'accion':check[state]
                }
        print(data)
        db.session.query(Component).filter(Component.id==r_component).update({'state':check[state]})
        db.session.add(accion_db(data))
        db.session.commit()
    return render_template('huerta/index.html', cultivos=cultivos, actions=actions, select=r_cultivo)



def accion_db(data):
    accion = Action()
    accion.cultivo_id = data['cultivo_id']
    accion.component_id = data['component_id']
    accion.time_action = data['time_action']
    accion.state = data['state']
    accion.accion = data['accion']
    return accion

src/src_app/app/templates/huerta/index.html
{% extends 'base/base.html'%}

{% block content %}

<div class="row">
    <div class="col-2">
        <!-- Form de cultivos-->    
        <form action="{{url_for('huerta.index')}}" method="POST">
            <select id="cultivo_select" name="num_cultivo" class="custom-select">
                {% for cultivo in cultivos %}
                <option value={{cultivo.id}}>{{cultivo.name}} </option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-default">Ir</button>
        </form>
    </div>
    <div class="col-10">
        {% for act in actions %}
        <div class="row">
            <div class="col-5">
                <h4>{{act.model}}</h4>
            </div>
            <div class="col-3">
                <input id={{act.id}} name="btn-action" type="checkbox">
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<!--img src="https://png.icons8.com/color/50/000000/water.png"-->
<!--img src="https://png.icons8.com/color/50/000000/fan.png"-->
<!--img src="https://png.icons8.com/color/50/000000/light.png"-->


{% for act in actions %}
<script>


var state = {};
state["1"] = "on";
state["0"] = "off";
$(function() {
    $(("#" + {{act.id}})).bootstrapToggle({
        on: 'Enabled',
        off: 'Disabled'
    });

    $(("#" + {{act.id}})).bootstrapToggle(state[{{act.state}}]);
    console.log(state[{{act.state}}]);

})
</script>
{% endfor %}


<script charset="utf-8">
$(function() {
console.log( {{select}} )
$("select option[value=" + {{select}} + "]").attr("selected",true);
})
</script>

<script charset="utf-8">

$(function () {
    $("input[name='btn-action']").change(function () {
       $.post("/huerta", {
       state:$(this).prop('checked'),
       id:$(this).attr('id'),
       cultivo_id:{{select}}
       })
       }); 
    console.log($(this).prop('checked'));
})    

</script>


{% endblock %}